name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Cake Action
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: default
