name: MacOs Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Cake Action
      uses: cake-build/cake-action@v1.3.0
      with:
        target: default
